0: begin print_char <= 72; print_counter <= print_counter + 1; print_en <= 1; end
1: begin print_char <= 69; print_counter <= print_counter + 1; print_en <= 1; end
2: begin print_char <= 76; print_counter <= print_counter + 1; print_en <= 1; end
3: begin print_char <= 76; print_counter <= print_counter + 1; print_en <= 1; end
4: begin print_char <= 79; print_counter <= print_counter + 1; print_en <= 1; end
5: begin print_char <= 32; print_counter <= print_counter + 1; print_en <= 1; end
6: begin print_char <= 69; print_counter <= print_counter + 1; print_en <= 1; end
7: begin print_char <= 67; print_counter <= print_counter + 1; print_en <= 1; end
8: begin print_char <= 53; print_counter <= print_counter + 1; print_en <= 1; end
9: begin print_char <= 53; print_counter <= print_counter + 1; print_en <= 1; end
10: begin print_char <= 49; print_counter <= print_counter + 1; print_en <= 1; end
11: begin print_char <= 46; print_counter <= print_counter + 1; print_en <= 1; end
12: begin print_char <= 13; print_counter <= print_counter + 1; print_en <= 1; end
13: begin print_char <= 77; print_counter <= print_counter + 1; print_en <= 1; end
14: begin print_char <= 89; print_counter <= print_counter + 1; print_en <= 1; end
15: begin print_char <= 32; print_counter <= print_counter + 1; print_en <= 1; end
16: begin print_char <= 78; print_counter <= print_counter + 1; print_en <= 1; end
17: begin print_char <= 65; print_counter <= print_counter + 1; print_en <= 1; end
18: begin print_char <= 77; print_counter <= print_counter + 1; print_en <= 1; end
19: begin print_char <= 69; print_counter <= print_counter + 1; print_en <= 1; end
20: begin print_char <= 32; print_counter <= print_counter + 1; print_en <= 1; end
21: begin print_char <= 73; print_counter <= print_counter + 1; print_en <= 1; end
22: begin print_char <= 83; print_counter <= print_counter + 1; print_en <= 1; end
23: begin print_char <= 58; print_counter <= print_counter + 1; print_en <= 1; end
24: begin print_char <= 32; print_counter <= print_counter + 1; print_en <= 1; end
25: begin print_char <= 66; print_counter <= print_counter + 1; print_en <= 1; end
26: begin print_char <= 79; print_counter <= print_counter + 1; print_en <= 1; end
27: begin print_char <= 88; print_counter <= print_counter + 1; print_en <= 1; end
28: begin print_char <= 13; print_counter <= print_counter + 1; print_en <= 1; end
29: begin print_char <= 80; print_counter <= print_counter + 1; print_en <= 1; end
30: begin print_char <= 76; print_counter <= print_counter + 1; print_en <= 1; end
31: begin print_char <= 69; print_counter <= print_counter + 1; print_en <= 1; end
32: begin print_char <= 65; print_counter <= print_counter + 1; print_en <= 1; end
33: begin print_char <= 83; print_counter <= print_counter + 1; print_en <= 1; end
34: begin print_char <= 69; print_counter <= print_counter + 1; print_en <= 1; end
35: begin print_char <= 32; print_counter <= print_counter + 1; print_en <= 1; end
36: begin print_char <= 69; print_counter <= print_counter + 1; print_en <= 1; end
37: begin print_char <= 78; print_counter <= print_counter + 1; print_en <= 1; end
38: begin print_char <= 84; print_counter <= print_counter + 1; print_en <= 1; end
39: begin print_char <= 69; print_counter <= print_counter + 1; print_en <= 1; end
40: begin print_char <= 82; print_counter <= print_counter + 1; print_en <= 1; end
41: begin print_char <= 32; print_counter <= print_counter + 1; print_en <= 1; end
42: begin print_char <= 65; print_counter <= print_counter + 1; print_en <= 1; end
43: begin print_char <= 32; print_counter <= print_counter + 1; print_en <= 1; end
44: begin print_char <= 77; print_counter <= print_counter + 1; print_en <= 1; end
45: begin print_char <= 79; print_counter <= print_counter + 1; print_en <= 1; end
46: begin print_char <= 68; print_counter <= print_counter + 1; print_en <= 1; end
47: begin print_char <= 69; print_counter <= print_counter + 1; print_en <= 1; end
48: begin print_char <= 58; print_counter <= print_counter + 1; print_en <= 1; end
49: begin print_char <= 13; print_counter <= print_counter + 1; print_en <= 1; end
default: begin print_char <= 0; print_en <= 0; print_done <= 1; end
